language: php
sudo: false
cache:
  apt: true
php:
  - 7.2
before_script:
  - composer install -n
script:
  - vendor/bin/codecept run unit --coverage --coverage-xml
after_script:
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then php vendor/bin/php-coveralls; fi
after_success:
  - travis_retry php vendor/bin/php-coveralls -v
  - vendor/bin/test-reporter
env:
  global:
  - secure: b8iwiVqNOgqDt/9PLTDhQsH5lNroAQaviRQ2naSTlK10V2EpcMjAnl5wplT7GShFPdqmWiHkhuNsHUFhEFM+1/ORuCgaqYSHWpWzvUp8hxE5YI/9qrItMelOSvB9WzTDQRZcYKkMUgBcpiZs1Pwm8szZOgmPPWYXjJCpjaEx2QyXtzHSi/nvodLQakZqMf75ND+Rp+2Y5z+FksPWbY8VY+Ke0HM/rVWb/fvRiTLDOW/tpQZmdutEuCJP/RTF4cbcwD1Zc3X8hLObavvDMRWK9rPcLPrDtVUMmBkawDsbizG/v1jhVuqmk80IV3Ckgo9yCJQvummsTMYzRrkPDxR1HcsGGUtTcPo4tQwfQZDGmpefNeknXw5tFy0jrnBoKQZn40T+pptaMY11zLa/i2HtYhs/bhIsBSHCxRTQNA9lVPTa/zx/s6U6GfFJPEd2pq+YQfG3grQGNnnNMp/JUbCg6bg5E4SIeWJaZweleMO0z3Kxo/K5yicYmqLs5VBQlX+7w+UrzaNNGR4Q5oJZokTIpRiGB1ImJgBQsaKQOudhKTN8NR0kfdhmZdXR7Lf+3GUSxLleph7Tg3fL18NGUnKWbaLMXHXNbxaNjSxjgeX2fdfKJfWJC43QM13Nng6z7wsAT/6SeiP30a4+2Na2i3C9qyTorlzpEx7SrwO/Ubb6N00=
  - secure: SPtiKwmsDK02pdIYl4vMKI9ElQzKTF1jnHnbATBLbfyLEVMocudQyJJJ2BMpQ0mJafQt2AMG6SmkrGvt+gxSfcxaGdl4/Iidne89PuefnAC9RmvzeQA5dSqfK066I3F3Qxw3/0B6yFEiFFABDUU48S1z477Xo8+OMYbCcr3wevtmvtHoQhh5uD2OSJ1GiZJjd8gyuIQlpOR1/tVl4ZAO4/fDuKKE31dLe55RmjP3RqIq9pSMsNdzrxTf3f8SqiGhHeLlw82ot+W+SwLd2GKkQnhD3QM7EH4JZxbTRmE/6hP9EYQ1p0XOjaJuaQE+vPdFU4eR+JzejxHIh5AqYsSg9HSH+DY8R9NePYR0bX/f+L4U0v7MNm4fHDfz8Y/srhYDrRcuHXShsVUVRKcjUjB2+CP5DfLNhX4uMQDupJytM0kCKGf7Zsymeqd+St0BS9mD48MkeRFyqvYt4bWGF98iYsznrGbS9d+7gHBhAuBonM3OPgmSGFb4fX7N0F3w/E6xlEryJZNQHWFEDioNPe4x1gbEvWmc/w1mqgKJD0kvcgmzrnPh1NOyifHUHtOqb54cPaecgTsgn+uxMi5MmeFYrnozXP+ZK0Gg2Sb8EJIJo8m9fTNWECZmcqCZ9KrRR/gWxx9s5N8FL1aBGS1SrjYm1PbZn6HEl+OJ3Y4t771vdPw=
  - secure: ciF0s5U5ldDOai2VU368vPjvMMM6g9gp6Swm04NLWhl4xdFovhjI6XRCKWsalYuR9pwQX9Jwnov6IbqrJUjsjqaqcNi0FH1Y/K3tzIz151hzufqFn2G3ftK8BAz/4HDM9ZOdWT4125Fmt5kc5X/RI/urZs/9TuhmdwXHLFrH5D6L6be8wE3m0Q2+1JbYZan49v+Ua6PQ6xPqrLSElqe5Wg/6kS3JaTd5POROjMCQXi2Ky9QVJdyALEFr++ZPrrDIs+40lohXJpMEI+IB3/EBP3DZMNk0V+UM+twpuu8PtXVRoMpX7CB3xkiIUGESFACbxE2jSVeYZQhKhAw5cgDhxdoK4dtvIEkHHCltuMlsEpmxEXK5Y6dnHCENkPUQtESpHOCvirK1KHuHpG2xK5iVAnDuMpP2hAClJozq8xvWpJUm2RebVp1sW0vVYAFnX2vRBs5+fCN9NhkJ4NeSZL+pq/Mvtj/HGUEbLMlWv7u2da3mEzfMC0C6FjxStHS7SneTAXNNpKd4P0hoc0Ea+OXd/R+ma6zM8vYk6RhDxG1QzlRPzghaMyr4FUN8BxhUkIn8Uki7SzyFXfl0T1xVA9Isxlt+9dRuQar2GZaKlEsx2HnAPm7jb6fcDBchIvXuw7JhBMa0MA6/XL2KmB+f8ubse28fYfjimAsYeBsKc0V6MSs=
